// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiFprBgBZjJ63WuDNJxR-9YsRL_skWFpA',
    appId: '1:483781811955:web:9a840f4d203f618f84a186',
    messagingSenderId: '483781811955',
    projectId: 'checkbird-d2804',
    authDomain: 'checkbird-d2804.firebaseapp.com',
    databaseURL: 'https://checkbird-d2804-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkbird-d2804.appspot.com',
    measurementId: 'G-8C4X2ZBM1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE9srFEVCARSKxg-FpztuGkfZKQ-l4eSs',
    appId: '1:483781811955:android:6e47664e9580171d84a186',
    messagingSenderId: '483781811955',
    projectId: 'checkbird-d2804',
    databaseURL: 'https://checkbird-d2804-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkbird-d2804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA48ISWW41lM-rvd5e2VjoyolOhprJzABU',
    appId: '1:483781811955:ios:b087a38a3d7fcbad84a186',
    messagingSenderId: '483781811955',
    projectId: 'checkbird-d2804',
    databaseURL: 'https://checkbird-d2804-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'checkbird-d2804.appspot.com',
    androidClientId: '483781811955-21s8h6csie3q6frrde084h93vui93q4a.apps.googleusercontent.com',
    iosClientId: '483781811955-rvs10a0h76esjljj5e5sf03r8umubgev.apps.googleusercontent.com',
    iosBundleId: 'com.techlosophy.checkBird',
  );
}
